FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git protobuf protobuf-dev

WORKDIR /build

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

COPY go.mod ./
RUN go mod download || true
COPY proto/ ./proto/
COPY master/ ./master/
COPY chunkserver/ ./chunkserver/

RUN mkdir -p proto/github.com/free-fs/proto && \
    protoc \
      --go_out=. \
      --go_opt=paths=source_relative \
      --go-grpc_out=. \
      --go-grpc_opt=paths=source_relative \
      proto/free_fs.proto || true

RUN ls proto/ 

COPY go.sum* ./

RUN go mod tidy 2>/dev/null || go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o master-server ./master/

FROM alpine:3.19

RUN apk add --no-cache ca-certificates netcat-openbsd

WORKDIR /app

COPY --from=builder /build/master-server .

RUN mkdir -p /data

EXPOSE 50051

CMD ["./master-server"]
