FROM golang:1.21-alpine
RUN apk add --no-cache protobuf-dev protoc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN PATH=$PATH:/go/bin protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/free_fs.proto
RUN go mod tidy
RUN go build -o /node cmd/node/main.go
EXPOSE 50051
CMD ["/node"]
