syntax = "proto3";
package pb;
option go_package = "github.com/s4nj1th/free-fs/proto;pb";

message PutRequest { string filename = 1; int32 num_chunks = 2; }
message PutResponse { repeated ChunkAssignment assignments = 1; bool success = 2; string error = 3; }
message ChunkAssignment { string chunk_handle = 1; repeated string chunkserver_ips = 2; }
message GetRequest { string filename = 1; }
message GetResponse { repeated ChunkAssignment chunks = 1; bool success = 2; string error = 3; }
message LsRequest {}
message LsResponse { repeated string filenames = 1; }
message StatRequest { string filename = 1; }
message StatResponse { int32 num_chunks = 1; bool success = 2; string error = 3; }
message ConfirmPutRequest { string filename = 1; }
message ConfirmPutResponse { bool success = 1; }

message WriteChunkRequest { string chunk_handle = 1; bytes data = 2; }
message WriteChunkResponse { bool success = 1; }
message ReadChunkRequest { string chunk_handle = 1; }
message ReadChunkResponse { bytes data = 1; bool success = 2; }

message HeartbeatRequest { int32 node_id = 1; }
message HeartbeatResponse { bool success = 1; }

message ElectionMessage { int32 sender_id = 1; }
message ElectionAnswer { bool ok = 1; }
message CoordinatorMessage { int32 sender_id = 1; }
message CoordinatorAnswer { bool ok = 1; }

service FreeFS {
    // Master endpoints
    rpc PutFile(PutRequest) returns (PutResponse);
    rpc ConfirmPut(ConfirmPutRequest) returns (ConfirmPutResponse);
    rpc GetFile(GetRequest) returns (GetResponse);
    rpc ListFiles(LsRequest) returns (LsResponse);
    rpc StatFile(StatRequest) returns (StatResponse);
    rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);

    // Chunkserver endpoints
    rpc WriteChunk(WriteChunkRequest) returns (WriteChunkResponse);
    rpc ReadChunk(ReadChunkRequest) returns (ReadChunkResponse);

    // Bully Algorithm
    rpc Election(ElectionMessage) returns (ElectionAnswer);
    rpc Coordinator(CoordinatorMessage) returns (CoordinatorAnswer);
}
